### ISSUE TITLE
Plug-in wants exec rights to /tmp folder

### ISSUE THREAD

**Issue by GB11111** [bwaldvogel/log4j-systemd-journal-appender#7]
Hello - This plug-in was working fine in our application, but then mysteriously stopped working. We are getting an UnsatisfiedLinkError /tmp/jna--1359426010/jna2000388232436467107.tmp message in the stack trace. The plug-in apparently uses JNA which in turn wants exec privileges to that subfolder. Temporarily removing noexec from /tmp in the Linux etc/fstab file resolves the problem, but this isn't something that should be granted on a permanent basis (it's a security issue).

Can you think of any reason why the plug-in would (now) need executable rights for a tmp file?  Is there a workaround?  Thank you!

**Comment by bwaldvogel** [comment]
Which version of log4j-systemd-journal-appender was working correctly for you and which version stopped working?

**Comment by GB11111** [comment]
Version 2.2.2 the entire time. It is possible that the system settings changed, as we have installed our application on different virtual machines. We will not have the authority to allow exec privileges to /tmp, though. Thanks.

**Comment by bwaldvogel** [comment]
I could reproduce your problem by setting `-Djna.tmpdir` to a mount with `noexec`.

Would it work for you to set `-Djna.tmpdir` to a location with exec permissions?

**Comment by GB11111** [comment]
I think this will work nicely -- thanks!
